/*
#autor: amirhosein ataei
#subject: Randon numbers generated by TinyOS, sending by Node-Red via MQTT to Thingspeak
*/

#ifndef TinyOS2NodeRed_H
#define TinyOS2NodeRed_H

typedef nx_struct _messageToSend {
        nx_uint16_t _MoteID;
        nx_uint16_t _dataMessage;
}_messageToSend_t;

enum{
    AM_MY_MSG = 6,
    _REDUCE_RANGE = 100,
    _FREQUENNCY = 5000,
};

#endif
